### PR TITLE
Fix dpservice-cli crash when running before initialisation

### LINKED ISSUE #639: dpservice-cli crashes when running commands before initialisation
**Describe the bug**
Dpservice-cli crashes when running commands before initialisation.
Not all commands have this issue; `list nats` ends correctly with error 

**To Reproduce**
Run dpservice and before initialisation via `dpservice-cli init` run commands:
```
# dpservice-cli list lbprefixes 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8acfd5]

goroutine 1 [running]:
github.com/ironcore-dev/dpservice/cli/dpservice-cli/cmd.RunListLoadBalancerPrefixes({0xa9ac88, 0xc00002e060}, {0xa95a00?, 0xc000012810?}, {0xa9ad68, 0xc000012900}, {{0x0, 0x0}, {0x0, 0x0}})
        /workspace/cli/dpservice-cli/cmd/list_loadbalancer_prefixes.go:79 +0x155
github.com/ironcore-dev/dpservice/cli/dpservice-cli/cmd.ListLoadBalancerPrefixes.func1(0xc0002c4300?, {0xe43d70?, 0x0?, 0x0?})
        /workspace/cli/dpservice-cli/cmd/list_loadbalancer_prefixes.go:32 +0x65
github.com/spf13/cobra.(*Command).execute(0xc0002c4300, {0xe43d70, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004600)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(0xc00011a738?)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x19
main.main()
        /workspace/cli/dpservice-cli/main.go:21 +0x55
```

**Expected behavior**
It should exit with error `not initialized` like when listing nats:
```
# dpservice-cli list nats
Error running command: error listing nats: rpc error: code = Aborted desc = not initialized
```

### PR DESCRIPTION
**Pull request by vlorinc**
Unify error handling accross all commands

- change in dpservice-go library: unified the return values of gRPC functions
- this fixes #639; empty struct is now always returned and accessing Status.Code field doesn't crash dpservice-cli
- changes in dpservice-cli: removed checking for Status.Code as it is handled by error value
- removed the check of Status.Code from RenderList(), Status is checked before, errorous Lists are not rendered and error is returned

Fixes #639

### CODE REVIEW

File: go/dpservice-go/client/client.go [hunk 1]
```diff
@@ -346,14 +356,19 @@ func (c *client) GetInterface(ctx context.Context, id string, ignoredErrors ...[
...
+			TypeMeta: api.TypeMeta{Kind: api.InterfaceListKind},
+			Status:   api.ProtoStatusToStatus(res.Status)}, errors.GetError(res.Status, ignoredErrors)
 	}
 
 	ifaces := make([]api.Interface, len(res.GetInterfaces()))
 	for i, dpdkIface := range res.GetInterfaces() {
 		iface, err := api.ProtoInterfaceToInterface(dpdkIface)
 		if err != nil {
-			return nil, err
+			return &api.InterfaceList{}, err
```
Comment (guvenc) [inline go/dpservice-go/client/client.go:371]: What is the affect of these changes to users of this library ? Did you check metalnet ?
In case of an error now no nil is returned as value but an empty list, could it be the case the library callers like metalnet were checking on nil ? or this would change their error behavior ?

**Review by guvenc — COMMENTED** [review]
Please see my question in the comments

**Review by guvenc — APPROVED** [review]
Thanks

**Comment by guvenc** [comment]
@vlorinc 
Could you please rebase to main ?
