### PR TITLE
Avoid using iteration to determine existence of a vnf value

### LINKED ISSUE #475: Slow data path for VM2VM on the same hypervisor
It was reported that the data path for VM2VM on the same hypervisor is slow. And I was able to reproduce it during recent tests, and it happens for IPv4 traffic.

### PR DESCRIPTION
**Pull request by byteocean**
fix #475

### CODE REVIEW

File: src/dp_vnf.c [hunk 1]
```diff
@@ -27,6 +35,46 @@ void dp_vnf_free(void)
...
+	ret = rte_hash_del_key(vnf_value_tbl, vnf);
+	if (DP_FAILED(ret)) {
+		DPS_LOG_ERR("Cannot delete VNF value from table", DP_LOG_RET(ret));
+		return DP_ERROR;
+	}
+
+	return DP_OK;
+}
+
+static bool dp_if_vnf_value_exists(struct dp_vnf *vnf)
```
Comment (PlagueCZ) [inline src/dp_vnf.c:64]: `if (dp_if_...` seems strange, `if (dp_vnf_value_exists())` sounds fine

File: src/dp_vnf.c [hunk 2]
```diff
@@ -27,6 +35,46 @@ void dp_vnf_free(void)
 	dp_free_jhash_table(vnf_handle_tbl);
 }
 
+static int dp_record_vnf_value(struct dp_vnf *vnf)
```
Comment (PlagueCZ) [inline src/dp_vnf.c:38]: This just may be my Slavic mind, but `record` sounds like a world record or music record and not "save" or "add" which this function does :)

File: src/dp_vnf.c [hunk 3]
```diff
@@ -65,6 +113,18 @@ int dp_add_vnf(const uint8_t ul_addr6[DP_VNF_IPV6_ADDR_SIZE], enum dp_vnf_type t
...
 	}
 
+	if (DP_FAILED(dp_record_vnf_value(vnf))) {
+		if (prefix->ip_type == RTE_ETHER_TYPE_IPV4)
+			DPS_LOG_WARNING("VNF value recording failed", DP_LOG_VNF_TYPE(type), DP_LOG_VNI(vni),
+							DP_LOG_PORTID(port_id), DP_LOG_IPV4(prefix->ipv4), DP_LOG_PREFLEN(prefix_len));
+		else
+			DPS_LOG_WARNING("VNF value recording failed", DP_LOG_VNF_TYPE(type), DP_LOG_VNI(vni),
+							DP_LOG_PORTID(port_id), DP_LOG_IPV6(prefix->ipv6), DP_LOG_PREFLEN(prefix_len));
+		dp_delete_vnf_value(vnf);
```
Comment (PlagueCZ) [inline src/dp_vnf.c:123]: If saving the value failed, then you should not roll it back here, but in the function that failed. Here it has no real effect of course, but in general, that is the pattern everywhere else.

File: src/dp_vnf.c [hunk 4]
```diff
@@ -89,6 +149,12 @@ int dp_del_vnf(const uint8_t ul_addr6[DP_VNF_IPV6_ADDR_SIZE])
 		return ret;
 	}
 
+	ret = dp_delete_vnf_value(vnf);
+	if (!DP_FAILED(ret)) {
+		DPGRPC_LOG_WARNING("Cannot delete VNF value record");
```
Comment (PlagueCZ) [inline src/dp_vnf.c:154]: Logging twice can sometimes be beneficial, so this is not a change request, just that you could maybe just log here (where there is more information) and simplify the wrapper for delete/record.

File: src/dp_vnf.c [hunk 5]
```diff
@@ -115,25 +181,16 @@ static __rte_always_inline bool dp_vnf_match(const struct dp_vnf *vnf, enum dp_v
...
-		if (dp_vnf_match(vnf, DP_VNF_TYPE_LB_ALIAS_PFX, port_id, vni, prefix_ip, prefix_len))
-			return true;
-	}
-	return false;
+	vnf.port_id = port_id;
+	vnf.vni = vni;
+	vnf.type = DP_VNF_TYPE_LB_ALIAS_PFX;
+	vnf.alias_pfx.length = prefix_len;
+	vnf.alias_pfx.ol.ip_type = prefix_ip->ip_type;
+	memcpy(&vnf.alias_pfx.ol, prefix_ip, sizeof(struct dp_ip_address));
```
Comment (PlagueCZ) [inline src/dp_vnf.c:191]: You should take advantage of the initialization code to prevent unneeded zeroing and then re-setting:
```
struct dp_vnf vnf = {
    .port_id = port_id,
    ... etc.
}
```
I *think* (but with relative confidence) that even `    .alias_pfx.ol = prefix_ip,` should work jsut fine as it is a shallow copy (even whough of an array).

**Review by PlagueCZ — CHANGES_REQUESTED** [review]

**Comment by guvenc** [comment]
@byteocean 
Automated tests fail. Could you take a look and fix that before we further comment the code ? Thanks.

File: src/dp_vnf.c (hunk 1 above)
Comment (byteocean) [reply src/dp_vnf.c:64]: changed.

File: src/dp_vnf.c (hunk 2 above)
Comment (byteocean) [reply src/dp_vnf.c:38]: ja, I was hesitating to use record as well. so changed to "add'

File: src/dp_vnf.c (hunk 3 above)
Comment (byteocean) [reply src/dp_vnf.c]: it was wrong auto-completed code. It should be rolling back the above step.

File: src/dp_vnf.c (hunk 5 above)
Comment (byteocean) [reply src/dp_vnf.c]: yeah, I changed to use the init form. and it works by judging from the test results.

**Comment by byteocean** [comment]
> @byteocean Automated tests fail. Could you take a look and fix that before we further comment the code ? Thanks.

it should be fixed now. the current code is also with changes following existing comments.

File: src/dp_vnf.c [hunk 6]
```diff
@@ -89,79 +148,78 @@ int dp_del_vnf(const uint8_t ul_addr6[DP_VNF_IPV6_ADDR_SIZE])
...
 {
 	struct dp_vnf *vnf;
 	uint32_t iter = 0;
 	int32_t ret;
 	const void *key;
 	int delete_count = 0;
 
+	if (DP_FAILED(dp_delete_vnf_value(target_vnf)))
+		return DP_GRPC_ERR_NOT_FOUND;
+
```
Comment (PlagueCZ) [inline src/dp_vnf.c:202]: Could you actually improve this further by storing the VNF key (IPv6) as data inside this new table? That way you can remove the (already marked unsafe) hash table traversal below and directly call `dp_del_vnf()` using that key.

I think you only need to change to `static int dp_add_vnf_value(struct dp_vnf *vnf, const uint8_t *ul_addr6)` I think.

This would also eliminate `dp_vnf_match()` from the looks of things.

**Review by PlagueCZ — CHANGES_REQUESTED** [review]
I don't see any problems now, but one thing is possible to do now and I think it should be part of this change.

File: src/dp_vnf.c (hunk 6 above)
Comment (byteocean) [reply src/dp_vnf.c:199]: the code is optimised to use newly added mapping, but as a separate commit.

File: include/dp_vnf.h [hunk 7]
```diff
@@ -17,6 +17,14 @@ extern "C" {
...
 #define DP_VNF_MATCH_ALL_PORT_IDS 0xFFFF
 
+#define DP_PRINT_VNF_OP_WARNING(MESSAGE, VNF) \
+		if (VNF->alias_pfx.ol.ip_type == RTE_ETHER_TYPE_IPV4) {\
+			DPS_LOG_WARNING(MESSAGE, DP_LOG_VNF_TYPE(VNF->type), DP_LOG_VNI(VNF->vni), \
+							DP_LOG_PORTID(VNF->port_id), DP_LOG_IPV4(VNF->alias_pfx.ol.ipv4), DP_LOG_PREFLEN(VNF->alias_pfx.length)); } \
+		else {\
+			DPS_LOG_WARNING(MESSAGE, DP_LOG_VNF_TYPE(VNF->type), DP_LOG_VNI(VNF->vni), \
+							DP_LOG_PORTID(VNF->port_id), DP_LOG_IPV6(VNF->alias_pfx.ol.ipv6), DP_LOG_PREFLEN(VNF->alias_pfx.length)); } \
+
```
Comment (PlagueCZ) [inline include/dp_vnf.h:27]: I like the encapsulation for more informative logs.
But, unless you aim to use this macro from another module, it would be best to keep in in the `.c` file. It also can be an inline instead of a macro.
And the name would better be `DP_LOG_VNF_WARNING`, as `PRINT` evokes `printf()`. Not sure what the `_OP_` means, I guess a typo of IP? But even then it is used even for non-IP related warnings, so that's why I would remove that infix also.

File: src/dp_vnf.c [hunk 8]
```diff
@@ -89,83 +156,52 @@ int dp_del_vnf(const uint8_t ul_addr6[DP_VNF_IPV6_ADDR_SIZE])
...
 		return ret;
 	}
 
+	ret = dp_delete_vnf_value(vnf);
+	if (DP_FAILED(ret)) {
+		DPGRPC_LOG_WARNING("Cannot delete VNF value record");
+		return ret;
+	}
+
+	rte_free(vnf);
```
Comment (PlagueCZ) [inline src/dp_vnf.c:171]: I think you also need to free this when `dp_delete_vnf_value()` fails, because the key is already gone from the `vnf_handle_tbl` thus making this an orphan pointer.

File: src/dp_vnf.c [hunk 9]
```diff
@@ -89,83 +156,52 @@ int dp_del_vnf(const uint8_t ul_addr6[DP_VNF_IPV6_ADDR_SIZE])
...
-					DPS_LOG_ERR("Cannot delete VNF key", DP_LOG_RET(ret), DP_LOG_VNF_TYPE(type), DP_LOG_PORTID(port_id),
-								DP_LOG_VNI(vni), DP_LOG_IPV4(prefix_ip->ipv4), DP_LOG_PREFLEN(prefix_len));
-				else
-					DPS_LOG_ERR("Cannot delete VNF key", DP_LOG_RET(ret), DP_LOG_VNF_TYPE(type), DP_LOG_PORTID(port_id),
-								DP_LOG_VNI(vni), DP_LOG_IPV6(prefix_ip->ipv6), DP_LOG_PREFLEN(prefix_len));
-			}
-		}
-	}
-	return delete_count > 0 ? DP_GRPC_OK : DP_GRPC_ERR_NOT_FOUND;
+	return DP_OK;
```
Comment (PlagueCZ) [inline src/dp_vnf.c:204]: You can actually just `return dp_del_vnf(vnf_ul_addr6);`

But saying that, this will in the end do another lookup into the `vnf_value_tbl`. So maybe splitting the `dp_del_vnf()` into `static dp_del_vnf_only()` that gets called here is in order (and then deleting from `vnf_value_tbl` explicitely here.

**Review by PlagueCZ — CHANGES_REQUESTED** [review]

File: include/dp_vnf.h (hunk 7 above)
Comment (byteocean) [reply include/dp_vnf.h:27]: I agree with the critics on including PRINT. The OP means operation, not a typo.

File: src/dp_vnf.c (hunk 8 above)
Comment (byteocean) [reply src/dp_vnf.c:171]: done.

File: src/dp_vnf.c (hunk 9 above)
Comment (byteocean) [reply src/dp_vnf.c:204]: it is really a refactoring effort here. It was a tricky to refactor as you suggested (splitting), since this function is heavily used (e.g., in grpc part). I would suggest to address as a separate PR.

**Comment by byteocean** [comment]
rebased to main.

File: src/dp_vnf.c [hunk 10]
```diff
@@ -27,6 +43,64 @@ void dp_vnf_free(void)
...
+		DPS_LOG_WARNING("VNF value allocation failed", DP_LOG_IPV6(ul_addr6));
+		return DP_ERROR;
+	}
+
+	memcpy(vnf_ul_addr6, ul_addr6, DP_IPV6_ADDR_SIZE);
+
+	ret = rte_hash_add_key_data(vnf_value_tbl, vnf, vnf_ul_addr6);
+	if (DP_FAILED(ret)) {
+		DPS_LOG_ERR("Cannot add VNF value and the corresponding underlying IPv6 address to table", DP_LOG_RET(ret));
+		return DP_ERROR;
```
Comment (PlagueCZ) [inline src/dp_vnf.c:62]: I am not sure how I missed this earlier, but you need to `rte_free(vnf_ul_addr6)` here

File: src/dp_vnf.c (hunk 8 above)
Comment (PlagueCZ) [reply src/dp_vnf.c:180]: You can make it neater if you free right before the DP_FAILED condition.

**Review by PlagueCZ — CHANGES_REQUESTED** [review]

File: src/dp_vnf.c (hunk 10 above)
Comment (byteocean) [reply src/dp_vnf.c:63]: Indeed, done

**Review by PlagueCZ — APPROVED** [review]

**Review by guvenc — APPROVED** [review]
Looks good to me.
